### ISSUE TITLE
New module(s) idea

### ISSUE THREAD

**Issue by samsonasik** [sitrunlab/LearnZF2#101]
Let's think about new module, I'm thinking about zend\crypt demo, more ideas are welcome ;)

**Comment by acelaya** [comment]
Navigation, permissions, log... I think all of them can be "easily"
explained in a module.

--
Alejandro Celaya Alastrué
http://www.alejandrocelaya.com

**Comment by samsonasik** [comment]
For Navigation idea, need separate layout, no?
For Permission idea, i like it, probably need login with like user & userpass and admin and adminpass with different link resource, yes?
For log idea, how we demonstrate date already logged? Read file?

Warm regards,

Abdul Malik Ikhsan

Pada 23 Jan 2015, pukul 13.31, Alejandro Celaya <notifications@github.com> menulis:

> Navigation, permissions, log... I think all of them can be "easily" 
> explained in a module. 
> 
> -- 
> Alejandro Celaya Alastrué 
> http://www.alejandrocelaya.com

**Comment by acelaya** [comment]
What do you think if we simplify that?

For **navigation**, the new module just needs to define the navigation configuration and then we could use it to render a fake menu on top of navigation documentation. It could have random hiperlinks to other webapges or sections in the website.

For **permissions** (at least with ACL), we could define the roles and display them in a select box. The visitor selects a role from the select and an ajax request returns the list of resources it is allowed to "use" and the permissions it has over them (view, edit...).

This way there is no need to implement a login, but maybe it is not a real enough example this way, what do you think.

For **log**... I don't know what's the best way to show the real behavior of the logger.

**Comment by samsonasik** [comment]
Yeah, we need simplify them. I agree with navigation, and permisssion. For log, I'm thinking about create a form with select priority of log : "emerg", "er", etc with simple formatter and  button "Create log" with Stream writer and write with 'php://output' and get its buffer in read-only text, what do you think ?

**Comment by acelaya** [comment]
I was thinking about that too. I think it's a good idea.

--
Alejandro Celaya Alastrué
www.alejandrocelaya.com

**Comment by samsonasik** [comment]
great! for zend\crypt, i don't have a real idea right now. probably implements navigation, permission, and log first is an imaginable implementation right now, what module do you want to pick first? so i can work on other(s).

**Comment by acelaya** [comment]
I could start with navigation if you are ok.

--
Alejandro Celaya Alastrué
www.alejandrocelaya.com

**Comment by samsonasik** [comment]
it's ok, thank you ;)

**Comment by acelaya** [comment]
I was thinking on new modules to add. Cache, EventManager and I18n shouldn't be too hard to implement. 
What do to think?

**Comment by samsonasik** [comment]
good idea. what module(s) do you want to pick?

**Comment by acelaya** [comment]
I don't know, I18n maybe? I could add some translations in English and
Spanish, and later add other languages with your help.

--
Alejandro Celaya Alastrué
www.alejandrocelaya.com

**Comment by samsonasik** [comment]
that's great ;). for Cache demo, is Memory adapter ok ? if yes, then I will do the Cache demo

**Comment by samsonasik** [comment]
or Filesystem adapter? seems ok too

**Comment by acelaya** [comment]
The filesystem adapter should be enough.

--
Alejandro Celaya Alastrué
www.alejandrocelaya.com

**Comment by samsonasik** [comment]
ok :+1:

**Comment by Stanimirdim92** [comment]
Hi, and thanks for allowing me.

I have an idea for a module based on Apache htpasswd authentication.
I can create a factory called AdapterFactoryAuthentication, which will consume Zend\Authentication\Adapter\Http and Zend\Authentication\Adapter\Http\FileResolver. The usernames and passwords will be stored in txt files. (passwords will be hashed of course.

**Comment by samsonasik** [comment]
Hi, I personally +1 for that, @acelaya any comment on this?

**Comment by acelaya** [comment]
Sounds good!

--
Alejandro Celaya Alastrué
www.alejandrocelaya.com

**Comment by Stanimirdim92** [comment]
Done. I will get onto it ASAP.

**Comment by Stanimirdim92** [comment]
Hi,

Looking all the form questions at the zf2 facebook group, I'm thinking that we should create few tutorials with different scenarios about how to create and use zf2 forms. 
What do you think? 

Regards,
Stanimir

**Comment by samsonasik** [comment]
Hi @Stanimirdim92 , well, I think that need long discussions, for how we pack them, but you can start with that ( probably create new issue with RFC to be discussed ? ).

I am currently planning to create in discussed new module idea, just still doesn't have enough time.

**Comment by Stanimirdim92** [comment]
Agree. That needs to be discussed. Maybe we can do a chat conversation this Friday or Sunday?

P.S I'm also a little busy these weeks due to huge amount of work and university duties.

**Comment by samsonasik** [comment]
@Stanimirdim92 skype meeting is ok for me. Many improvements instead of new module that need to be discussed ( feature, style, etc). My time is GMT+7, I hope I will be available from Sunday 10.00 PM my time. /cc @acelaya @mockiemockiz

**Comment by Stanimirdim92** [comment]
I'm GMT+3. Sunday, I will be available from 02.00-03.00 PM, which is exactly around 10.00 PM your time.

**Comment by samsonasik** [comment]
@acelaya @mockiemockiz please let me know your availability for talk, thank you

**Comment by acelaya** [comment]
Sorry, the last month has been a nightmare.
I won't be able this weekend. I'll be traveling without computer, I'm
sorry.

--
Alejandro Celaya Alastrué
www.alejandrocelaya.com

**Comment by samsonasik** [comment]
it's ok. ok then, we will re-arrange the time next week

**Comment by mockiemockiz** [comment]
I prefer Saturday at anytime but Sunday 10.00 OR 11.00 PM is OK. give me the date.. I need to setup my alarm..

**Comment by Stanimirdim92** [comment]
I'm not sure If I will be free the next Sunday. However, count me free for now. What about this Friday?

**Comment by acelaya** [comment]
Not possible for me, sorry.

--
Alejandro Celaya Alastrué
www.alejandrocelaya.com

**Comment by Stanimirdim92** [comment]
Should be plan another meeting this weekend?

**Comment by samsonasik** [comment]
Yes, I will be available at weekend, what day/time will you all available?

Warm regards,

Abdul Malik Ikhsan

Pada 25 Mei 2015, pukul 20.26, Stanimir Dimitrov <notifications@github.com> menulis:

**Comment by acelaya** [comment]
I will be available this weekend too. I'm GMT+2

**Comment by Stanimirdim92** [comment]
GMT +3, but Saturday only from 6PM. Sunday I'm free whole day.

**Comment by acelaya** [comment]
I prefer Sunday too

2015-05-25 21:07 GMT+02:00 Stanimir Dimitrov <notifications@github.com>:

> GMT +3, but Saturday only from 6PM. Sunday I'm free whole day.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sitrunlab/LearnZF2/issues/101#issuecomment-105290773>.
>



-- 
Alejandro Celaya Alastrué
http://www.alejandrocelaya.com

**Comment by samsonasik** [comment]
I created time poll for Sunday http://doodle.com/ygshw7bscb693g47 ( GMT + 7 on mine ), please select time on there for time availability on Sunday, If you need specific add more day/time, let me know.
Thank you.

**Comment by Stanimirdim92** [comment]
I have another crazy idea :D.

Can we get a partnership with the people responsible for ZF2 and start writing/posting tutorials on their website? This way way more people would see all the tutorials and hopefully learn more. Also a IRC notification on the #zftalk channel would be nice.

**Comment by samsonasik** [comment]
I personally not sure with that approach. They currently busy for major version, and probably be annoying to notify on #zftalk ... btw I hope we can discuss more on meeting this weekend

Warm regards,

Abdul Malik Ikhsan

Pada 26 Mei 2015, pukul 19.36, Stanimir Dimitrov <notifications@github.com> menulis:

**Comment by samsonasik** [comment]
Hi @acelaya @mockiemockiz please confirm your availability at sunday at http://doodle.com/ygshw7bscb693g47 or here so we can get the time, Thank you

**Comment by acelaya** [comment]
Sorry, I completly forgot this.
Just answered the doodle.

**Comment by samsonasik** [comment]
@acelaya it's ok, Thank you. Currently we have 1 match time ( 11:00 PM GMT+7 ) based on http://doodle.com/ygshw7bscb693g47 . 
@mockiemockiz if you want another time to pick, please write, thank you.

**Comment by samsonasik** [comment]
Hi All, I'm online at skype now ;) /cc @acelaya @mockiemockiz @Stanimirdim92

**Comment by acelaya** [comment]
Me too

**Comment by Stanimirdim92** [comment]
Some new module ideas.

- Controller Plugin. How to create a plugin and pass all dependencies like service manager and controller plugin manager. A real world example would fit perfectly such as using FlashMessenger to pass arrays|strings|arrayobjects which can be iterated with \Spl libraries and showed to the user after a redirect. Bootstrap can be used for message styling in combination with FM namespace.

- ZF2 optimizations and performance tricks such as: autoload_classmap.php, template_map, cache module config, setting different layouts without EdpModuleLayouts. More?

**Comment by samsonasik** [comment]
in my opinion, 

1. controller plugins sample is ok.
2. Not sure about optimizations, as it looks should be a blog post instead of real live example. note: autoload_classmap in zf2 can be replaced with composer autoload.

Warm regards,

Abdul Malik Ikhsan

Pada 8 Agt 2015, pukul 15.15, Stanimir Dimitrov <notifications@github.com> menulis:
